Add posibility to add several devices
wirenboard/wb-mqtt-urri pull request #12
Opened 2023-12-26 13:24 UTC by ekateluv

Добавила возможность добавления нескольких ресиверов urri

2023-12-26 13:24 UTC, ekateluv commented
![изображение](https://github.com/wirenboard/wb-mqtt-urri/assets/97599621/72b18eae-6ef8-4492-8734-2af95c397327)

2023-12-26 21:07 UTC, sikmir commented on debian/changelog
> +wb-mqtt-urri (1.0.9) stable; urgency=medium
```suggestion
wb-mqtt-urri (1.1.0) stable; urgency=medium
```

2023-12-26 21:10 UTC, sikmir commented on debian/changelog
> +  * Add posibility to add several urri devices
```suggestion
  * Add possibility to add several urri devices
```

2023-12-26 21:14 UTC, sikmir commented on debian/control
> +Depends: ${misc:Depends}, python3:any (>= 3.9.0), python3-wb-common (>= 2.1.0~~), python3-socketio, python3-requests, python3-pyinotify, python3-websocket, python3-jsonschema
От nm_helper еще зависит

2023-12-26 21:17 UTC, sikmir commented on wb-mqtt-urri.conf
> +            "urri_port": 9032,
```suggestion
            "urri_port": 9032
```

2023-12-26 21:23 UTC, sikmir commented on wb-mqtt-urri.schema.json
> +                "urri_ip": {
Может `pattern` добавить для валидации

2023-12-26 21:25 UTC, sikmir commented on wb-mqtt-urri.schema.json
> +                    "default": 9032,
```suggestion
                    "default": 9032,
                    "minimum": 0,
                    "maximum": 65535
```

2023-12-26 21:33 UTC, sikmir commented
Сейчас можно добавить несколько девайсов с одинаковым `device_id`.

2023-12-26 22:00 UTC, sikmir commented on wb-mqtt-urri
> +        return True if "1" in str(response.content) else False
```suggestion
        return "1" in str(response.content)
```

2023-12-26 22:02 UTC, sikmir commented on wb-mqtt-urri
> +        if volume >= 0 and volume <= 100:
```suggestion
        if 0 <= volume <= 100:
```

2023-12-26 22:11 UTC, sikmir commented on wb-mqtt-urri
> +                        sourcetype = "Unknown"
```suggestion
                    source_types = {
                        0: "Internet Radio",
                        1: "File System",
                        2: "Preset",
                        3: "Multiroom Slave",
                        4: "Airplay",
                        5: "User Internet Radio",
                        6: "Spotify",
                    }
                    sourcetype = source_types.get(type_id, "Unknown")
```

2023-12-27 04:40 UTC, KraPete requested changes
Мы сломали обратную совместимость со старыми конфигами. Если обновиться, то ранее сконфигурированное устройство отвалится

2023-12-27 13:54 UTC, sikmir commented on debian/wb-mqtt-urri.install
> +/bin/wb-mqtt-urri /usr/bin
```suggestion
bin/wb-mqtt-urri /usr/bin
```

2023-12-27 13:57 UTC, sikmir commented on wb-mqtt-urri.conf
> +    ],
автоформатирование
```suggestion
    "devices": [
        {
            "device_id": "urri",
            "device_title": "Network Receiver URRI",
            "urri_ip": "",
            "urri_port": 9032
        }
    ],
```

2023-12-28 07:30 UTC, ekateluv commented
> * Сейчас можно добавить несколько девайсов с одинаковым `device_id`
> 
>     * Можно добавить `device_id` уже существующий (например `buzzer`) и получить конфликт
> 
>     * Если конфиг не валидный, то сервис имеет `status=1/FAILURE` и рестартует. Тут лучше вернуть `status=6/NOTCONFIGURED` и не рестартовать (`RestartPreventExitStatus=6`).

1, 3. Сделала. Насчет 2 не все так просто. Как понять, что уже есть устройство с таким же mqtt-именем? А что если просто подправили конфиг (например, порт) и новое устройство опознается как дубликат старого? Можно конечно подвязаться к имени, типа если title устройства и mqtt топика совпадают, то это то же самое устройство. А если я в конфиге title поменяю? Тогда по логике мы должны без конфликта опубликовать новые данные, но опять не стыкуется: если mqtt одинаковое но title разное, выглядит как будто мы пытаемся в какое то существующее другое устройство писать. Может я не учла чего то, но вроде у нас в проектах пока что нет проверок такого плана...

2023-12-28 13:15 UTC, sikmir commented on wb_mqtt_urri/main.py
> +            wbmqtt.ControlMeta(title="Воспроизведение", control_type="switch", order=3, read_only=False),
Сейчас локализации контролов нет, все остальные на английском, может и тут не переводить?

2023-12-28 13:24 UTC, sikmir commented on wb_mqtt_urri/main.py
> +    logger.setLevel(logging.DEBUG if bool(config["debug"]) else logging.INFO)
"debug" может отсутствовать в конфиге:
```sh
/usr/bin/wb-mqtt-urri
Traceback (most recent call last):
  File "/usr/bin/wb-mqtt-urri", line 8, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.9/dist-packages/wb_mqtt_urri/main.py", line 413, in main
    logger.setLevel(logging.DEBUG if bool(config["debug"]) else logging.INFO)
KeyError: 'debug'
```

2023-12-28 13:25 UTC, sikmir commented on wb_mqtt_urri/main.py
> +    for json_device in config["devices"]:
"devices" тоже  может не быть

2024-01-09 10:48 UTC, ekateluv commented on wb_mqtt_urri/main.py
> +def to_json(config_filepath: str) -> dict:
В required было только ip и port, исправила чтобы и другие поля не сломались

2024-01-09 11:26 UTC, KraPete approved these changes

2024-01-09 12:34 UTC, merged