Rework topic tree, add translations, add name in config
wirenboard/wb-mqtt-urri pull request #9
Opened 2023-05-11 16:40 UTC by schtangel

- Changed the order of controls
- Add control Radio ID
- Add name and title to configuration
- Changed meta to json format

2023-05-11 17:47 UTC, sikmir commented
Хорошо бы явно указать версию схемы, например `"$schema": "http://json-schema.org/draft-07/schema#"`

2023-05-11 18:28 UTC, schtangel commented
Посмотрел - у нас везде draft-04. Её и указал.

2023-05-12 11:35 UTC, vdromanov commented on wb-mqtt-urri
> -    mqttClient.publish("/devices/urri/meta/name", "Network reciever URRI", retain=True)
а name точно больше не нужен?

2023-05-12 11:40 UTC, vdromanov commented on wb-mqtt-urri
> +root_topic = "/devices/" + device_id
вот лично мне сложение строк сильно режет глаз

можно на форматную строчку переделать везде
root_topic = "/devices/%s" % device_id

но не особо настаиваю

2023-05-12 11:41 UTC, vdromanov commented on wb-mqtt-urri
> -    mqttClient.publish("/devices/urri/meta/name", "Network reciever URRI", retain=True)
про title ru то же самое

2023-05-12 11:41 UTC, schtangel commented on wb-mqtt-urri
> -    mqttClient.publish("/devices/urri/meta/name", "Network reciever URRI", retain=True)
Ну вряд ли оно будет использоваться на старых релизах, так что вроде и не за чем.

2023-05-12 11:42 UTC, vdromanov commented on wb-mqtt-urri
> +        "title": {"ru": "Громкость"},
английский не нужен?

2023-05-12 11:43 UTC, vdromanov commented on wb-mqtt-urri
> +        "title": {"ru": "Громкость"},
и везде дальше

2023-05-12 11:45 UTC, vdromanov requested changes
а вот на чем настаиваю - на описании PRа, понятном человеку

в случае какой-либо лажи, мы возвращаемся к старым PR и внимательно читаем

2023-05-12 11:49 UTC, schtangel commented on wb-mqtt-urri
> -    mqttClient.publish("/devices/urri/meta/name", "Network reciever URRI", retain=True)
title ru осознанно снесли - у нас тайтл меняется в конфигураторе

2023-05-12 11:52 UTC, vdromanov approved these changes
@aadegtyarev погонял; давай описание, и потом squash & merge

2023-05-12 11:53 UTC, schtangel commented on wb-mqtt-urri
> +        "title": {"ru": "Громкость"},
м, а это, похоже, ошибка.

2023-05-12 11:54 UTC, schtangel commented on wb-mqtt-urri
> +        "title": {"ru": "Громкость"},
м, а это, похоже, ошибка.

2023-05-12 12:02 UTC, schtangel commented on wb-mqtt-urri
> +        "title": {"ru": "Громкость"},
А, нет - это так и задумывалось - в английском варианте сам топик имеет правильный вид

2023-05-12 12:15 UTC, schtangel commented on wb-mqtt-urri
> +root_topic = "/devices/" + device_id
хорошо, это поисправляем массово тогда, когда будем там что-то менять

2023-05-12 12:15 UTC, merged